package com.base_module.constants

import com.base_module.BuildConfig

object SharedPrefConstant {

    const val PREF_LOGIN_CREDENTIAL = "prefLoginCredential"
    const val ON_BOARDING = "on_boarding"
    const val NIGHT_MODE = "night_mode"
    const val CONFIG_DATA = "config_data"
    const val IS_FIRST_LOAD_CONFIG = "IS_FIRST_LOAD_CONFIG"
    const val FEED_DATA_PREF = "FEED_DATA_PREF"
    const val GENERAL_THEME = "general_theme"
    const val ACCESS_TOKEN = "access_token"
    const val LAST_ITERATION_OCCURED_TIME = "update_screen_time"
    const val HAS_DEVICE_INFO_SAVED = "has_device_info_saved_new"
    const val SIM_CARD_LIST = "sim_card_list"
    const val POPUP_WINDOW_Y_AXIS = "popup_window_x_axis"
    const val REFRESH_TOKEN = "refresh_token"
    const val USER_LANGUAGE = "user_language"
    const val USER_DEFAULT_LANGUAGE = "en"
    const val IS_LANGUAGE_SELECTED = "en"
    const val USER_NAME = "user_name"
    const val IS_INTERNAL_USER = "is_internal_user"
    const val OTP_CONTACT_NUMBER = "otp_contact_number"
    const val OTP_CONTACT_MAIL = "otp_contact_mail"
    const val SKIP_EMAIL_VERIFICATION = "skip_email_verification"
    const val PROFILE_ICON = "profile_icon"
    const val FEED_MESSAGES = "founders_message"
    const val SHARE_TEXT = "share_text"
    const val PRIVACY_POLICY_URL = "PRIVACY_POLICY_URL"
    const val TERMS_AND_SERVICE_URL = "TERMS_AND_SERVICE_URL"
    const val COOKIES_POLICY_URL = "COOKIES_POLICY_URL"
    const val SEARCH_SYNC_AFTER_X_TIME= "SEARCH_SYNC_AFTER_X_TIME"
    const val SYNC_AFTER_X_TIME = "SYNC_AFTER_X_TIME"
    const val FAQ_URL = "FAQ_URL"
    const val IS_ON_BOARDING_DONE = "is_on_boarding_done"
    const val PROFILE_NAME = "profile_name"
    const val START_CALLER_ID_RECEIVER_SERVICE = "START_CALLER_ID_RECEIVER_SERVICE"
    const val HAS_CALLER_ID_SERVICE_STARTED_ONCE = "HAS_CALLER_ID_SERVICE_STARTED_ONCE"
    const val HOME_VIDEO_URL = "home_video_url"
    const val LOGIN_VIDEO_URL = "LOGIN_video_url"
    const val IS_AUDIO_MUTE = "is_audio_mute"
    const val EMAIL_RESEND_COUNTER = "email_resend_counter"
    const val MOBILE_RESEND_COUNTER = "mobile_resend_counter"
    const val VIBRATE_ON_KEY_PRESS = "vibrate_on_key_press"
    const val SERVICE_METHOD = "service_method"
    //const val SPEAK_CALLER_NAME = "SPEAK_CALLER_NAME"

    const val FRIENDS_MAPPING_SYNC_TIME = "friends_maping_sync_time"
    const val LAST_FRIENDS_MAPPING_SYNC_TIME = "LAST_FRIENDS_MAPPING_SYNC_TIME"

    const val LAST_HEART_BEAT_SYNC_TIME = "LAST_HEART_BEAT_SYNC_TIME"
    const val HEART_BEAT_SYNC_TIME = "HEART_BEAT_SYNC_TIME"

    const val SHOW_POP_UP_ON_EVERY_CALL = "show_pop_up_on_every_call"
    const val SHOW_POP_UP_AFTER_CALL_END = "show_pop_up_after_call_end"
    const val DARK_MODE = "enable_disable_the_dark_mode"
    const val REFERRAL_CODE = "referral_code"
    const val PERSONAL_REFERRAL_CODE = "personal_referral_code"
    const val COUNTER_FOR_CARDS = "counter_for_cards"
    const val AlREADY_RATED_THE_APP = "already_rated_the_app"

    const val READ_ALOUD = "read_aloud"
    const val VOICE_CONTROLS = "voice_controls"
    const val FAKE_A_CALL = "fake_a_call"
    const val INCOGNITO = "incognito"
    const val PREMIUM_BADGE = "premium_badge"
    const val PROFILE_VISITORS = "profile_visitors"
    const val ANNOUNCE_ON_HEADPHONE = "announce_on_headphone"
    const val ANNOUNCE_BHARATACALLER_CONTACTS = "announce_bharatcaller_contacts"
    const val ANNOUNCE_SAVED_CONTACTS = "announce_saved_contacts"
}
